//! Rust sources for `crates/diavolo-format/src/generated/`: constants and the rule
//! taxonomy. No decoding logic is generated; the decoder is hand-written.

use std::fmt::Write;

use crate::spec::{Format, Rules, rule_variant, type_size};

const BANNER: &str =
    "// @generated by `cargo xtask codegen` from docs/spec/. DO NOT EDIT: CI fails on any diff.\n";

fn upper(s: &str) -> String {
    s.to_ascii_uppercase()
}

pub fn mod_rs() -> String {
    format!(
        "{BANNER}\n//! Generated from `docs/spec/`. See `docs/generated/format.md`.\n\npub mod layout;\npub mod rules;\n"
    )
}

pub fn layout_rs(f: &Format) -> String {
    let mut s = String::from(BANNER);
    s += "\n//! Byte-layout constants. Offsets are in bytes from the start of the record.\n\n";
    s += "#![allow(dead_code)]\n\n";
    s += "use crate::field::{Bytes, I64, U16, U32, U64};\n\n";

    let _ = writeln!(
        s,
        "/// Vocabulary version of the spec YAML this was generated from."
    );
    let _ = writeln!(s, "pub const SPEC_SCHEMA: u32 = {};", f.spec_schema);
    let _ = writeln!(
        s,
        "/// Format version a writer built from this spec writes."
    );
    let _ = writeln!(
        s,
        "pub const FORMAT_MAJOR: u16 = {};",
        f.format_version.major
    );
    let _ = writeln!(
        s,
        "pub const FORMAT_MINOR: u16 = {};",
        f.format_version.minor
    );
    let _ = writeln!(
        s,
        "/// Every (major, minor) a reader accepts. Everything else is rejected."
    );
    let rows: Vec<String> = f
        .acceptance
        .rows
        .iter()
        .map(|r| format!("({}, {})", r.file_major, r.file_minor))
        .collect();
    let _ = writeln!(
        s,
        "pub const ACCEPTED_VERSIONS: &[(u16, u16)] = &[{}];\n",
        rows.join(", ")
    );
    let _ = writeln!(s, "/// Bits at odd positions in a u32 flags field.");
    let _ = writeln!(s, "pub const ODD_BITS_U32: u32 = 0xAAAA_AAAA;\n");

    for c in &f.constants {
        let _ = writeln!(s, "/// {}", c.doc);
        let _ = writeln!(s, "pub const {}: u64 = {};", c.name, c.value);
    }
    s += "\n";
    for m in &f.magics {
        let bytes: Vec<String> = m.bytes.iter().map(|b| format!("0x{b:02X}")).collect();
        let _ = writeln!(s, "/// {}", m.doc);
        let _ = writeln!(s, "pub const {}: [u8; 8] = [{}];", m.name, bytes.join(", "));
    }

    for en in &f.enums {
        let _ = writeln!(s, "\npub mod {} {{", en.name);
        if let Some(mask) = en.mask {
            let _ = writeln!(
                s,
                "    /// Applied to the containing field before comparing."
            );
            let _ = writeln!(s, "    pub const MASK: {} = 0x{mask:04X};", en.width);
        }
        for v in &en.values {
            let _ = writeln!(s, "    /// {}", v.doc);
            let _ = writeln!(
                s,
                "    pub const {}: {} = 0x{:04X};",
                upper(&v.name),
                en.width,
                v.value
            );
        }
        let defined: Vec<String> = en
            .values
            .iter()
            .filter(|v| v.value != 0 && !v.registered_undefined)
            .map(|v| upper(&v.name))
            .collect();
        let reg: Vec<String> = en
            .values
            .iter()
            .filter(|v| v.registered_undefined)
            .map(|v| upper(&v.name))
            .collect();
        let _ = writeln!(s, "    /// Values a reader accepts.");
        let _ = writeln!(
            s,
            "    pub const DEFINED: &[{}] = &[{}];",
            en.width,
            defined.join(", ")
        );
        let _ = writeln!(
            s,
            "    /// Registered names with no defined meaning: rejected like unknown values."
        );
        let _ = writeln!(
            s,
            "    pub const REGISTERED_UNDEFINED: &[{}] = &[{}];",
            en.width,
            reg.join(", ")
        );
        let names: Vec<String> = en
            .values
            .iter()
            .map(|v| format!("({}, {:?})", upper(&v.name), v.name))
            .collect();
        let _ = writeln!(
            s,
            "    pub const NAMES: &[({}, &str)] = &[{}];",
            en.width,
            names.join(", ")
        );
        s += "}\n";
    }

    s += "\n/// content_kind values admitted for each file_type.\n";
    s += "pub const CONTENT_KIND_BY_TYPE: &[(u32, &[u16])] = &[\n";
    for (t, kinds) in &f.content_kind_by_type {
        let ks: Vec<String> = kinds
            .iter()
            .map(|k| format!("content_kind::{}", upper(k)))
            .collect();
        let _ = writeln!(s, "    (file_type::{}, &[{}]),", upper(t), ks.join(", "));
    }
    s += "];\n";

    for fs_ in &f.flag_sets {
        let _ = writeln!(
            s,
            "\n/// Even/odd convention; unknown odd bits violate `{}`.",
            fs_.unknown_odd_rule
        );
        let _ = writeln!(s, "pub mod {} {{", fs_.name);
        let mut known = Vec::new();
        for b in &fs_.bits {
            let _ = writeln!(s, "    /// {}", b.doc);
            let _ = writeln!(s, "    pub const {}: u32 = 1 << {};", upper(&b.name), b.bit);
            known.push(upper(&b.name));
        }
        let known = if known.is_empty() {
            "0".to_string()
        } else {
            known.join(" | ")
        };
        let _ = writeln!(s, "    pub const KNOWN: u32 = {known};");
        let _ = writeln!(
            s,
            "    pub const UNKNOWN_ODD: u32 = super::ODD_BITS_U32 & !KNOWN;"
        );
        s += "}\n";
    }

    s += "\npub mod block_type {\n";
    for bt in &f.block_types {
        let _ = writeln!(s, "    /// {} ({})", bt.doc, bt.status);
        let _ = writeln!(s, "    pub const {}: [u8; 4] = *b\"{}\";", bt.id, bt.id);
    }
    let pick = |st: &str| -> String {
        f.block_types
            .iter()
            .filter(|b| b.status == st)
            .map(|b| b.id.clone())
            .collect::<Vec<_>>()
            .join(", ")
    };
    let _ = writeln!(
        s,
        "    pub const DEFINED: &[[u8; 4]] = &[{}];",
        pick("defined")
    );
    let _ = writeln!(
        s,
        "    pub const REGISTERED_UNDEFINED: &[[u8; 4]] = &[{}];",
        pick("registered_undefined")
    );
    s += "}\n";

    for l in &f.layouts {
        let _ = writeln!(s, "\n/// {}", l.doc);
        let _ = writeln!(s, "pub mod {} {{", l.name);
        let _ = writeln!(s, "    use super::*;\n");
        let _ = writeln!(s, "    pub const LEN: usize = {};", l.size);
        for fl in &l.fields {
            if let Some(d) = &fl.doc {
                let _ = writeln!(s, "    /// {d}");
            }
            let ty = match fl.ty.as_str() {
                "u16" => "U16".to_string(),
                "u32" => "U32".to_string(),
                "u64" => "U64".to_string(),
                "i64" => "I64".to_string(),
                b => format!("Bytes<{}>", type_size(b).unwrap_or(0)),
            };
            let ctor = ty.split('<').next().unwrap_or(&ty).to_string();
            let _ = writeln!(
                s,
                "    pub const {}: {ty} = {ctor}({});",
                upper(&fl.name),
                fl.off
            );
        }
        let reserved: Vec<String> = l
            .fields
            .iter()
            .filter(|x| x.reserved)
            .map(|x| format!("({}, {})", x.off, type_size(&x.ty).unwrap_or(0)))
            .collect();
        let _ = writeln!(
            s,
            "    /// (offset, length) of every field that MUST be zero."
        );
        let _ = writeln!(
            s,
            "    pub const RESERVED: &[(usize, usize)] = &[{}];",
            reserved.join(", ")
        );
        let heap: Vec<String> = l
            .heap_refs
            .iter()
            .map(|(o, n)| {
                format!(
                    "({:?}, {}.0, {}.0)",
                    o.trim_end_matches("_off"),
                    upper(o),
                    upper(n)
                )
            })
            .collect();
        let _ = writeln!(
            s,
            "    /// (name, offset field position, length field position) of every heap reference."
        );
        let _ = writeln!(
            s,
            "    pub const HEAP_REFS: &[(&str, usize, usize)] = &[{}];",
            heap.join(", ")
        );
        let fields: Vec<String> = l
            .fields
            .iter()
            .map(|x| {
                format!(
                    "({:?}, {}, {})",
                    x.name,
                    x.off,
                    type_size(&x.ty).unwrap_or(0)
                )
            })
            .collect();
        let _ = writeln!(
            s,
            "    /// (name, offset, length) of every field, in order."
        );
        let _ = writeln!(
            s,
            "    pub const FIELDS: &[(&str, usize, usize)] = &[{}];",
            fields.join(", ")
        );
        s += "}\n";
    }

    s += "\n/// A table inside the INDX payload. `record_len` is None for a table with no\n";
    s += "/// defined record, whose count must be zero.\n";
    s += "pub struct IndexTable {\n    pub name: &'static str,\n    pub record_len: Option<usize>,\n    pub count_off: usize,\n    pub count_len: usize,\n}\n\n";
    s += "/// Tables in on-disk order after the index header; the heap follows the last.\n";
    s += "pub const INDEX_TABLES: &[IndexTable] = &[\n";
    let ih = f.layout("index_header");
    for t in &f.index_tables {
        let cf = ih.and_then(|l| l.field(&t.count));
        let (off, len) = cf
            .map(|c| (c.off, type_size(&c.ty).unwrap_or(0)))
            .unwrap_or((0, 0));
        let rec = match &t.record {
            Some(r) => format!("Some({r}::LEN)"),
            None => "None".into(),
        };
        let _ = writeln!(
            s,
            "    IndexTable {{ name: {:?}, record_len: {rec}, count_off: {off}, count_len: {len} }},",
            t.name
        );
    }
    s += "];\n\n";
    let phases: Vec<String> = f.phases.iter().map(|p| format!("{:?}", p.name)).collect();
    let _ = writeln!(
        s,
        "/// Verification phases, in the order a reader performs them."
    );
    let _ = writeln!(s, "pub const PHASES: &[&str] = &[{}];", phases.join(", "));
    s
}

pub fn rules_rs(r: &Rules) -> String {
    let mut s = String::from(BANNER);
    s += "\n//! The rule taxonomy. A decoder rejection names exactly one `Rule`.\n\n";
    s += "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\npub enum Level {\n    Must,\n    Should,\n}\n\n";
    s += "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\npub enum Scope {\n    File,\n    Chain,\n    Writer,\n    Behaviour,\n}\n\n";
    s += "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\npub enum Rule {\n";
    for x in &r.rules {
        let _ = writeln!(s, "    /// `{}`: {}", x.id, x.text);
        let _ = writeln!(s, "    {},", rule_variant(&x.id));
    }
    s += "}\n\nimpl Rule {\n";
    s += "    /// Every rule, in rules.yaml order (which is check order within a phase).\n";
    s += "    pub const ALL: &'static [Rule] = &[\n";
    for x in &r.rules {
        let _ = writeln!(s, "        Rule::{},", rule_variant(&x.id));
    }
    s += "    ];\n\n";

    let arm = |s: &mut String, sig: &str, f: &dyn Fn(&crate::spec::Rule) -> String| {
        let _ = writeln!(s, "    pub const fn {sig} {{\n        match self {{");
        for x in &r.rules {
            let _ = writeln!(s, "            Rule::{} => {},", rule_variant(&x.id), f(x));
        }
        s.push_str("        }\n    }\n\n");
    };
    arm(&mut s, "id(self) -> &'static str", &|x| {
        format!("{:?}", x.id)
    });
    arm(&mut s, "level(self) -> Level", &|x| {
        if x.level == "MUST" {
            "Level::Must".into()
        } else {
            "Level::Should".into()
        }
    });
    arm(&mut s, "scope(self) -> Scope", &|x| {
        match x.scope.as_str() {
            "file" => "Scope::File",
            "chain" => "Scope::Chain",
            "writer" => "Scope::Writer",
            _ => "Scope::Behaviour",
        }
        .into()
    });
    arm(
        &mut s,
        "phase(self) -> Option<&'static str>",
        &|x| match &x.phase {
            Some(p) => format!("Some({p:?})"),
            None => "None".into(),
        },
    );
    arm(&mut s, "text(self) -> &'static str", &|x| {
        format!("{:?}", x.text)
    });
    arm(&mut s, "fixtures(self) -> &'static [&'static str]", &|x| {
        let v: Vec<String> = x.fixtures.iter().map(|f| format!("{f:?}")).collect();
        format!("&[{}]", v.join(", "))
    });
    s += "    pub fn from_id(id: &str) -> Option<Rule> {\n        Self::ALL.iter().copied().find(|r| r.id() == id)\n    }\n}\n\n";
    s += "impl core::fmt::Display for Rule {\n    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {\n        f.write_str(self.id())\n    }\n}\n";
    s
}
