//! Rendered documentation for `docs/generated/`. Derived from the spec; never edited.

use std::fmt::Write;

use crate::spec::{Format, Rules, type_size};

const BANNER: &str = "<!-- @generated by `cargo xtask codegen` from docs/spec/. DO NOT EDIT: CI fails on any diff. -->\n";

fn cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

pub fn format_md(f: &Format) -> String {
    let mut s = String::from(BANNER);
    let _ = writeln!(
        s,
        "\n# Diavolo archive format {}.{} ({})\n",
        f.format_version.major, f.format_version.minor, f.status
    );
    if f.status == "UNSTABLE" {
        s += "> **UNSTABLE.** Archives in this format may become unreadable by later builds. Readers refuse every version not listed under *Acceptance*.\n\n";
    }
    let _ = writeln!(
        s,
        "Spec schema {}. Integers are {}-endian. Offsets are from {} unless stated. Reasons for these decisions: `docs/design/0001-archive-layout.md`.\n",
        f.spec_schema, f.endianness, f.offset_origin
    );

    s += "## Acceptance\n\n| file major | file minor | verdict |\n|---|---|---|\n";
    for r in &f.acceptance.rows {
        let _ = writeln!(s, "| {} | {} | {} |", r.file_major, r.file_minor, r.verdict);
    }
    let _ = writeln!(s, "| *any other* | | {} |\n", f.acceptance.otherwise);

    s += "## Physical layout\n\n```\noffset 0                 header        (header.LEN bytes)\n                         block*        (block_header + payload, tiling)\ntrailer.index_offset     INDX block    (block_header + index payload)\nEOF - trailer.LEN        trailer\n```\n\n";

    s += "## Constants\n\n| name | value | meaning |\n|---|---|---|\n";
    for c in &f.constants {
        let _ = writeln!(s, "| `{}` | {} | {} |", c.name, c.value, cell(&c.doc));
    }
    for m in &f.magics {
        let hex: Vec<String> = m.bytes.iter().map(|b| format!("{b:02X}")).collect();
        let _ = writeln!(
            s,
            "| `{}` | `{}` | {} |",
            m.name,
            hex.join(" "),
            cell(&m.doc)
        );
    }

    s += "\n## Enumerations\n\nValue 0 is `invalid` in every enumeration. Values not listed, and registered-but-undefined values, are rejected.\n";
    for en in &f.enums {
        let _ = writeln!(s, "\n### `{}` ({})\n", en.name, en.width);
        if let Some(mask) = en.mask {
            let _ = writeln!(s, "Compared after masking with `0x{mask:04X}`.\n");
        }
        s += "| value | name | meaning |\n|---|---|---|\n";
        for v in &en.values {
            let reg = if v.registered_undefined {
                " *(registered, undefined)*"
            } else {
                ""
            };
            let _ = writeln!(
                s,
                "| 0x{:04X} | `{}`{reg} | {} |",
                v.value,
                v.name,
                cell(&v.doc)
            );
        }
    }
    s += "\n### content_kind admitted per file_type\n\n| file_type | content_kind |\n|---|---|\n";
    for (t, k) in &f.content_kind_by_type {
        let _ = writeln!(
            s,
            "| `{t}` | {} |",
            k.iter()
                .map(|x| format!("`{x}`"))
                .collect::<Vec<_>>()
                .join(", ")
        );
    }

    s += "\n## Flag sets\n\nEvery flag set follows the even/odd convention: an unknown bit at an even position is ignored; an unknown bit at an odd position rejects the file.\n";
    for fs_ in &f.flag_sets {
        let _ = writeln!(
            s,
            "\n### `{}` ({}; unknown odd bit: `{}`)\n",
            fs_.name, fs_.width, fs_.unknown_odd_rule
        );
        if fs_.bits.is_empty() {
            s += "No bits defined.\n";
            continue;
        }
        s += "| bit | name | meaning |\n|---|---|---|\n";
        for b in &fs_.bits {
            let _ = writeln!(s, "| {} | `{}` | {} |", b.bit, b.name, cell(&b.doc));
        }
    }

    s += "\n## Block types\n\n| id | status | meaning |\n|---|---|---|\n";
    for b in &f.block_types {
        let _ = writeln!(s, "| `{}` | {} | {} |", b.id, b.status, cell(&b.doc));
    }

    s += "\n## Layouts\n";
    for l in &f.layouts {
        let _ = writeln!(s, "\n### `{}` — {} bytes\n\n{}\n", l.name, l.size, l.doc);
        s += "| offset | size | field | type | constraint | meaning |\n|---|---|---|---|---|---|\n";
        for fl in &l.fields {
            let mut c = Vec::new();
            if let Some(e) = &fl.enum_ {
                c.push(format!("enum `{e}`"));
            }
            if let Some(x) = &fl.flags {
                c.push(format!("flags `{x}`"));
            }
            if fl.reserved {
                c.push("MUST be 0".into());
            }
            let _ = writeln!(
                s,
                "| {} | {} | `{}` | {} | {} | {} |",
                fl.off,
                type_size(&fl.ty).unwrap_or(0),
                fl.name,
                fl.ty,
                c.join(", "),
                cell(fl.doc.as_deref().unwrap_or(""))
            );
        }
        if !l.heap_refs.is_empty() {
            let refs: Vec<String> = l
                .heap_refs
                .iter()
                .map(|(o, n)| format!("(`{o}`, `{n}`)"))
                .collect();
            let _ = writeln!(s, "\nHeap references: {}.", refs.join(", "));
        }
    }

    s += "\n## Index payload\n\nAfter `index_header`, in this order:\n\n| # | table | record | count field |\n|---|---|---|---|\n";
    for (i, t) in f.index_tables.iter().enumerate() {
        let rec = t
            .record
            .as_deref()
            .map(|r| format!("`{r}`"))
            .unwrap_or_else(|| "*none defined; count MUST be 0*".into());
        let _ = writeln!(
            s,
            "| {} | `{}` | {rec} | `index_header.{}` |",
            i + 1,
            t.name,
            t.count
        );
    }
    let _ = writeln!(
        s,
        "\nThen the heap: `{}` bytes, following {}. Heap offsets are from the {}.\n",
        f.heap.length_field, f.heap.follows, f.heap.offset_origin
    );

    s += "## Verification phases\n\nA reader performs these in order and reports the first violated rule (see `rules.md`).\n\n| # | phase | covers |\n|---|---|---|\n";
    for (i, p) in f.phases.iter().enumerate() {
        let _ = writeln!(s, "| {} | `{}` | {} |", i + 1, p.name, cell(&p.doc));
    }

    s += "\n## Normative notes that are not rules\n\n";
    for n in &f.notes {
        let _ = writeln!(s, "- {} *(Not a rule: {})*", n.text, n.not_a_rule_because);
    }
    s
}

pub fn rules_md(f: &Format, r: &Rules) -> String {
    let mut s = String::from(BANNER);
    let _ = writeln!(
        s,
        "\n# Diavolo format rules ({} total)\n\nEvery `file` and `chain` rule has broken fixtures in `corpus/broken/`, each violating exactly that rule.\n",
        r.rules.len()
    );
    for p in &f.phases {
        let _ = writeln!(
            s,
            "## Phase `{}`\n\n{}\n\n| id | level | rule | fixtures |\n|---|---|---|---|",
            p.name, p.doc
        );
        for x in r
            .rules
            .iter()
            .filter(|x| x.phase.as_deref() == Some(p.name.as_str()))
        {
            let fx: Vec<String> = x.fixtures.iter().map(|n| format!("`{n}`")).collect();
            let _ = writeln!(
                s,
                "| `{}` | {} | {} | {} |",
                x.id,
                x.level,
                cell(&x.text),
                fx.join(", ")
            );
        }
        s += "\n";
    }
    s += "## Writer and behaviour obligations\n\n| id | level | scope | rule | why no fixture |\n|---|---|---|---|---|\n";
    for x in r.rules.iter().filter(|x| x.phase.is_none()) {
        let _ = writeln!(
            s,
            "| `{}` | {} | {} | {} | {} |",
            x.id,
            x.level,
            x.scope,
            cell(&x.text),
            cell(x.no_fixture_because.as_deref().unwrap_or(""))
        );
    }
    s
}
